# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text='URL slug for the page (e.g., "about", "contact")',
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Page title for SEO", max_length=255
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="Meta description for SEO"),
                ),
                (
                    "h1_tag",
                    models.CharField(
                        blank=True, help_text="H1 heading for the page", max_length=255
                    ),
                ),
                (
                    "use_h1_in_hero",
                    models.BooleanField(
                        default=False,
                        help_text="Use H1 tag inside hero block instead of separately",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Canonical URL for SEO", max_length=500
                    ),
                ),
                (
                    "custom_head_html",
                    models.TextField(
                        blank=True,
                        help_text="Custom HTML to inject in <head> (tracking scripts, etc.)",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords for AI content generation (one per line)",
                    ),
                ),
                (
                    "lsi_phrases",
                    models.TextField(
                        blank=True,
                        help_text="LSI phrases for AI content generation (one per line)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "db_table": "pages",
                "ordering": ["site", "slug"],
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("article", "Article/Text Content"),
                            ("image", "Image Block"),
                            ("text_image", "Text + Image Combination"),
                            ("cta", "Call to Action"),
                            ("faq", "FAQ Section"),
                            ("swiper", "Game Carousel (Swiper)"),
                        ],
                        help_text="Type of content block",
                        max_length=20,
                    ),
                ),
                (
                    "content_data",
                    models.JSONField(
                        default=dict,
                        help_text="Block content stored as JSON (flexible structure)",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page Block",
                "verbose_name_plural": "Page Blocks",
                "db_table": "page_blocks",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="SwiperPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Preset name (e.g., "Top 10 Slots", "New Games")',
                        max_length=255,
                    ),
                ),
                (
                    "games_data",
                    models.JSONField(
                        help_text="Array of game objects with name, image, description, etc."
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Play Now",
                        help_text="Default button text for games in this preset",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Swiper Preset",
                "verbose_name_plural": "Swiper Presets",
                "db_table": "swiper_presets",
                "ordering": ["-created_at"],
            },
        ),
    ]
