# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        ("pages", "0001_initial"),
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="swiperpreset",
            name="affiliate_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Affiliate link for all games in this preset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swiper_presets",
                to="sites.affiliatelink",
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="pages.page",
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="AI prompt used to generate content for this block",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_blocks",
                to="prompts.prompt",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="sites.site",
            ),
        ),
        migrations.AddIndex(
            model_name="pageblock",
            index=models.Index(
                fields=["page", "order_index"], name="page_blocks_page_id_1dd154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageblock",
            index=models.Index(
                fields=["block_type"], name="page_blocks_block_t_f7b218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["site"], name="pages_site_id_acf58a_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["slug"], name="pages_slug_2ebe9d_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["site", "slug"], name="pages_site_id_26c203_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("site", "slug")},
        ),
    ]
