# Generated by Django 4.2.7 on 2025-10-19 08:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("media", "0001_initial"),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("click_tracking", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Affiliate Link",
                "verbose_name_plural": "Affiliate Links",
                "db_table": "affiliate_links",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("brand_name", models.CharField(max_length=255)),
                ("language_code", models.CharField(default="en-EN", max_length=10)),
                (
                    "template_variables",
                    models.JSONField(
                        default=dict, help_text="Custom values for template variables"
                    ),
                ),
                (
                    "custom_colors",
                    models.JSONField(
                        default=dict,
                        help_text="Customized color values if template supports it",
                    ),
                ),
                (
                    "unique_class_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Unique CSS class prefix for this site",
                        max_length=50,
                    ),
                ),
                (
                    "enable_page_speed",
                    models.BooleanField(
                        default=True,
                        help_text="Enable page speed optimizations (img to picture tags)",
                    ),
                ),
                ("allow_indexing", models.BooleanField(default=True)),
                ("redirect_404_to_home", models.BooleanField(default=False)),
                ("use_www_version", models.BooleanField(default=False)),
                ("custom_css_class", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="sites.affiliatelink",
                    ),
                ),
                (
                    "cloudflare_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="integrations.cloudflaretoken",
                    ),
                ),
                (
                    "favicon_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favicon_sites",
                        to="media.media",
                    ),
                ),
                (
                    "logo_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logo_sites",
                        to="media.media",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="templates.template",
                    ),
                ),
                (
                    "template_footprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="CMS footprint configuration for this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="templates.templatefootprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "db_table": "sites",
            },
        ),
    ]
