# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["user"], name="sites_user_id_c6b128_idx"),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["domain"], name="sites_domain_27d5c3_idx"),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["language_code"], name="sites_languag_94c36c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["template"], name="sites_templat_4c69ba_idx"),
        ),
    ]
