# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visitors", models.IntegerField(default=0)),
                ("pageviews", models.IntegerField(default=0)),
                (
                    "bounce_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_session_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Average session duration in seconds",
                        null=True,
                    ),
                ),
                (
                    "traffic_source",
                    models.CharField(
                        blank=True,
                        help_text="organic, direct, referral, social, paid",
                        max_length=100,
                    ),
                ),
                (
                    "conversions",
                    models.IntegerField(
                        default=0, help_text="Number of affiliate link clicks or goals"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Estimated revenue from affiliate commissions",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
                "db_table": "analytics",
            },
        ),
    ]
