# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics",
                to="sites.site",
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["site", "date"], name="analytics_site_id_55f975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(fields=["date"], name="analytics_date_f1f7af_idx"),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["traffic_source"], name="analytics_traffic_fb0117_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analytics",
            unique_together={("site", "date", "traffic_source")},
        ),
    ]
