# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("git_commit_hash", models.CharField(blank=True, max_length=40)),
                ("build_log", models.TextField(blank=True)),
                ("deployed_url", models.URLField(blank=True, max_length=500)),
                ("build_time_seconds", models.IntegerField(blank=True, null=True)),
                ("file_count", models.IntegerField(blank=True, null=True)),
                ("total_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "template_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of template, footprint, and variables used in this deployment",
                    ),
                ),
                (
                    "generated_files",
                    models.JSONField(
                        default=list, help_text="List of all generated file paths"
                    ),
                ),
                (
                    "unique_identifiers",
                    models.JSONField(
                        default=dict,
                        help_text="Unique class prefixes, image dimensions, etc. used in this deployment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cloudflare_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="integrations.cloudflaretoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment",
                "verbose_name_plural": "Deployments",
                "db_table": "deployments",
                "ordering": ["-created_at"],
            },
        ),
    ]
