# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        ("deployment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployments",
                to="sites.site",
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(fields=["site"], name="deployments_site_id_afc239_idx"),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(fields=["status"], name="deployments_status_a4a398_idx"),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["created_at"], name="deployments_created_6a65c1_idx"
            ),
        ),
    ]
