# Generated by Django 4.2.7 on 2025-10-19 08:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("chatgpt", "ChatGPT"),
                            ("grok", "Grok"),
                            ("claude", "Claude"),
                            ("cloudflare", "Cloudflare"),
                            ("elevenlabs", "ElevenLabs"),
                            ("dalle", "DALL-E"),
                            ("midjourney", "Midjourney"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token_value",
                    models.TextField(
                        help_text="API token/key (will be encrypted in production)",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "db_table": "api_tokens",
            },
        ),
        migrations.CreateModel(
            name="CloudflareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "account_id",
                    models.CharField(
                        blank=True, help_text="Cloudflare account ID", max_length=100
                    ),
                ),
                (
                    "zone_id",
                    models.CharField(
                        blank=True,
                        help_text="Cloudflare zone ID for DNS operations",
                        max_length=100,
                    ),
                ),
                (
                    "pages_project_name",
                    models.CharField(
                        blank=True,
                        help_text="Default Pages project name",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloudflare_configs",
                        to="integrations.apitoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloudflare Token",
                "verbose_name_plural": "Cloudflare Tokens",
                "db_table": "cloudflare_tokens",
            },
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(
                fields=["service"], name="api_tokens_service_aab213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(
                fields=["is_active"], name="api_tokens_is_acti_949075_idx"
            ),
        ),
    ]
