# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text Generation"),
                            ("image", "Image Generation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        blank=True,
                        help_text="Associated page block type: article, title, description, faq, hero",
                        max_length=100,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        help_text="AI model: gpt-4, gpt-3.5-turbo, claude-3, dall-e-3, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.7,
                        help_text="Creativity level (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, help_text="Maximum tokens for generation", null=True
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="Prompt template with variable placeholders: {keywords}, {brand_name}, etc."
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt for ChatGPT/Claude models"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "db_table": "prompts",
                "indexes": [
                    models.Index(fields=["type"], name="prompts_type_1520f2_idx"),
                    models.Index(
                        fields=["block_type"], name="prompts_block_t_8dbf1b_idx"
                    ),
                    models.Index(
                        fields=["ai_model"], name="prompts_ai_mode_b367c9_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="prompts_is_acti_e4fc17_idx"
                    ),
                ],
            },
        ),
    ]
