# Generated by Django 4.2.7 on 2025-10-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_media",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(
                fields=["parent_folder"], name="media_folde_parent__4bf48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafolder",
            index=models.Index(fields=["name"], name="media_folde_name_b7bef1_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["folder"], name="media_folder__433f55_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["uploaded_by"], name="media_uploade_e556e4_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["mime_type"], name="media_mime_ty_b43728_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["created_at"], name="media_created_3b0875_idx"),
        ),
    ]
